name: Java CI with Maven

on:
  push:
    branches: [main]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Install Chrome
      run: |
        $chromeInstallerUrl = 'https://dl.google.com/chrome/install/375.126/chrome_installer.exe'
        $chromeInstallerPath = "$env:TEMP\chrome_installer.exe"

        Invoke-WebRequest -Uri $chromeInstallerUrl -OutFile $chromeInstallerPath -UseBasicParsing
        Start-Process -FilePath $chromeInstallerPath -Wait -PassThru

        Remove-Item -Path $chromeInstallerPath

    - name: Run Tests
      run: mvnw.cmd test
